### ISSUE TITLE
Add possibility to return values instead of $q.when

### ISSUE THREAD

**Issue by dejakob** [showpad/angular-q-spread#12]
Add a posibility that when one of the methods returns a value, the spread still gets resolved...

**Comment by Etheryte** [comment]
Can you create an example demonstrating your desired use-case?

**Comment by klaascuvelier** [comment]
I'm not really sure what the TS is asking here, but it sounds like he wants the `$q.all` to resolve even when it would fail with a regular `then`? 
If this would be the request, I don't think it would be possible, as that is changing the behaviour of `$q.all`, not `spread`.
